version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: WarrenEverestDotnetDb
      MYSQL_USER: gregoryzimmerwarren
      MYSQL_PASSWORD: warren123
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '3306:3306'